services:
  fastapi:
    build: .
    container_name: fastapi-app
    command: uvicorn main:app --host 0.0.0.0 --port 11000
    ports:
      - "11000:11000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: prices

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

  streamlit:
    image: python:3.12.8-slim
    container_name: streamlit-app
    command: >
      sh -c "pip install --no-cache-dir streamlit requests && streamlit run app.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - fastapi


volumes:
  mongo_data:
